#!name=QPin iOS Network Location
#!desc=Modify Apple WiFi/cell network location (gs-loc) | Free tool by QPin | Not GPS | Upstream: Yu9191/wloc
#!author=QPin (based on Yu9191/wloc)
#!homepage=__APP_BASE__

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body __SCRIPT_BASE__/qpin-nl.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/qpin-nl\/settings url script-echo-response __SCRIPT_BASE__/qpin-nl-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
